### ISSUE TITLE
Add bill totals to app

### ISSUE THREAD

**Issue by jcbwlkr** [hitjim/ting-bill-split#5]
So I'm not super sure how this one should go down. There are at least 6 values we need from the bill PDF or as many as 10 if we're being detailed. It would be wonderful to just read them out of the pdf but I don't see that happening in v1.

We could add 6-10 more flags to the command but that seems like a burden.

We could add just 1 flag that points to a toml file with the bill totals. That would be simple enough I think. Okay yeah, maybe for v1 let's just do that. So like `-bill` and it points to a file like `bill.toml` that looks like this

```
minutes = 35.00
messages = 8.00
megabytes = 20.00
devices = 42.00
extras = 1.00
fees = 12.84
```

The main program should use https://github.com/BurntSushi/toml to open the file with `os.Open` and pass that file to a function
```
function parseBills(r io.Reader) (bills, error)
```

the return value should be defined like this

```
type bills struct {
	Minutes   float64 `toml:"minutes"`
	Messages  float64 `toml:"messages"`
	Megabytes float64 `toml:"megabytes"`
	Devices   float64 `toml:"devices"`
	Extras    float64 `toml:"extras"`
	Fees      float64 `toml:"fees"`
}
```

**Comment by hitjim** [comment]
Don't worry, I've got this.

**Comment by hitjim** [comment]
Ok start worrying b/c I forgot everything I thought I was doing with this.

**Comment by jcbwlkr** [comment]
I was just remembering this :)

*COMMENCES WORRYING*

**Comment by hitjim** [comment]
OK ... ONLY 85% WORRYTIME.
